version: 1.0.{build}


init:
- cmd: >-
    set xunit20=C:\Tools\xunit20

    set path=C:\Tools\xUnit;%path%

    set path=c:\Tools\NUnit3\bin;%path% 

install:
- cmd: nuget restore
build:  
  verbosity: minimal
#test:
 # assemblies:
  #- NUnit3TestProject.dll
  #- NUnit3TestProject2.dll
  #- XUnit20TestProject.DLL
  #try specific file
  #- NUnit3TestProject\bin\Debug\NUnit3TestProject.dll
  

test:
  assemblies:
    except:
#    - NUnit3TestProject.dll
#    - NUnit3TestProject2.dll
    - XUnit20TestProject.DLL
    - XUnitTestProject.dll
#    - NUnitTestProject.dll
#    - MsTestUnitTestProject.dll
